config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  resources :chat_rooms, only: [:create, :show, :index]
  match '/users', to:'static_pages#show', via: 'get'
  match '/chat_rooms/new/(:id)', to:'chat_rooms#new', via: 'get', as: 'new_chat_room'
  match '/users/ban/(:id)', to:'static_pages#ban', via: 'post', as:'ban'
  match '/users/unban/(:id)', to:'static_pages#unban', via: 'post', as: 'unban'

  devise_for :users, controllers: { sessions: "users/sessions",
                                    registrations: "users/registrations"}

  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end

  def show
    @users = User.all
    unless user_signed_in?
      flash[:danger]="Для просмотра всех пользователей требуется войти в существующий аккаунт, либо зарегистрироваться"
      redirect_to root_path
    end
  end

  def ban
    if current_user.admin?
      u = User.where(id: params[:id]).first
      if u
        u.ban = true
        u.save!

        redirect_to users_path, alert: "Пользователь #{u.email} был заблокирован"
      else
        redirect_to users_path, alert: "Пользователь #{u.email} не найден!"
      end
    else
      flash[:denger]="У вас нет доступа к данной функции!"
    end
  end

  def unban
    if current_user.admin?
      u = User.where(id: params[:id]).first
      if u
        u.ban = false
        u.save!

        redirect_to users_path, alert: "Пользователь #{u.email} был разблокирован!"
      else
        redirect_to users_path, alert: "Пользователь #{u.email} не найден!"
      end
    else
      flash[:denger]="У вас нет доступа к данной функции!"
    end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/index.html.erb
<div class="center hero-unit">
  <h1>Добро пожаловать в Сhat v1.0</h1>

  <h2> Чат будет доступен после регистрации/входа!</h2>

  <%= link_to "Зарегистрироваться", new_user_registration_path, class: "btn btn-large btn-primary" %>
</div>

app/views/static_pages/show.html.erb
<h1>Список всех пользователей</h1>

<div class="container-center">
  <% @users.each do |user| %>
    <div class="row user-ws">
      <div class="user-block">
          <%= gravatar_for user %>
          <%= user.name %>
          <% unless current_user.id == user.id %>
            <%= link_to "Создать чат", new_chat_room_path(user.id), class:'btn btn-primary btn-md' %>

            <% if current_user.admin %>
              <% if user.ban %>
              <%= link_to "Разблокировать", unban_path(user.id), method: :post, class:'btn btn-primary btn-md' %>
              <% else %>
                <%= link_to "Заблокировать", ban_path(user.id), method: :post, class:'btn btn-primary btn-md' %>
              <% end %>
            <% end %>
          <% end %>
      </div>
    </div>
  <% end %>
</div>