config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  resources :chat_rooms, only: [:create, :show, :index]
  match '/users', to:'static_pages#show', via: 'get'
  match '/chat_rooms/new/(:id)', to:'chat_rooms#new', via: 'get', as: 'new_chat_room'
  match '/users/ban/(:id)', to:'static_pages#ban', via: 'post', as:'ban'
  match '/users/unban/(:id)', to:'static_pages#unban', via: 'post', as: 'unban'

  devise_for :users, controllers: { sessions: "users/sessions",
                                    registrations: "users/registrations"}

  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  before_action :access_to_chat, only: [:show]

  def index
    @chat_rooms = ChatRoom.all
    @chat_rooms_for_user = ChatRoom.where(chat_to_user: current_user.id)
  end

  def show
    @chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
    @message = Message.new
  end

  def new
    @chat_to_user = params['id']
    @chat_room = ChatRoom.new
  end

  def create
    @chat_to_user = params['chat_to_user']
    @chat_room = current_user.chat_rooms.build(chat_room_params)
    if @chat_room.save
      flash[:success] = 'Chat room added!'
      redirect_to chat_rooms_path
    else
      render 'new'
    end
  end

  private

  def chat_room_params
    params.require(:chat_room).permit(:title, 'chat_to_user')
  end

  def access_to_chat
    unless current_user.chat_rooms.where("id=?", params[:id]).any? || ChatRoom.where(chat_to_user: current_user.id).where("id=?", params[:id]).any? || current_user.admin?
      redirect_to root_path
      flash[:danger]="У вас нет доступа к данному чату"
    end
  end

end

app/views/chat_rooms/_chat_room.html.erb
<li><%= link_to "Войти в чат> #{chat_room.title}", chat_room_path(chat_room) %></li>

app/views/chat_rooms/index.html.erb
<% if current_user.admin? %>
  <h1>Все чаты (только для модератора)</h1>
  <ul class="list-unstyled">
    <%= render @chat_rooms %>
  </ul>
<% end %>

<ul class="list-unstyled">
<% if current_user.chat_rooms.any? %>
  <h2>Чаты которые вы создали:</h2>
  <% current_user.chat_rooms.each do |chat_room| %>
    <li><%= link_to "Войти в чат > #{chat_room.title}", chat_room_path(chat_room) %></li>
  <% end %>
  <% else %>
    <h2>У вас нету созданных чатов =) </h2>
  <% end %>
</ul>

<ul class="list-unstyled">
<% if @chat_rooms_for_user.any? %>
<h2>Чаты где вам написали:</h2>
 <% @chat_rooms_for_user.each do |chat_room| %>
<li><%= link_to "Войти в чат > #{chat_room.title}", chat_room_path(chat_room) %></li>
  <% end %>
  <% else %>
    <h2>Вам никто не писал =) </h2>
  <% end %>
</ul>

app/views/chat_rooms/new.html.erb
<div class="container">
  <h1>Создание чата =)</h1>
  <%= form_for @chat_room do |f| %>
    <div class="form-group">
      <%= hidden_field_tag 'chat_room[chat_to_user]', @chat_to_user %>
      <%= f.label :title, 'Название чата' %>
      <%= f.text_field :title, autofocus: true, class: 'form-control' %>
    </div>
    <%= f.submit "Создать", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/chat_rooms/show.html.erb
<div class="container chat_room">
<h1><%= @chat_room.title %></h1>

  <div id="messages" data-chat-room-id="<%= @chat_room.id %>">
    <%= render @chat_room.messages %>
  </div>

  <%= form_for @message, url: '#' do |f| %>
    <div class="form-group">
      <%= f.label :body, 'Сообщение' %>
      <%= f.text_area :body, class: 'form-control' %>
      <small class="text-muted">Сообщение должно быть более 2-х символов</small>
    </div>

    <%= f.submit "Отправить", class: 'btn btn-primary btn-lg' %>

</div>
 <% end %>