config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  resources :chat_rooms, only: [:create, :show, :index]
  match '/users', to:'static_pages#show', via: 'get'
  match '/chat_rooms/new/(:id)', to:'chat_rooms#new', via: 'get', as: 'new_chat_room'
  match '/users/ban/(:id)', to:'static_pages#ban', via: 'post', as:'ban'
  match '/users/unban/(:id)', to:'static_pages#unban', via: 'post', as: 'unban'

  devise_for :users, controllers: { sessions: "users/sessions",
                                    registrations: "users/registrations"}

  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
 <footer>
   <p>by ShrewHools 2016 All Rights Reserved </p>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar  navbar-inverse">
  <nav>
    <ul class="nav pull-left">
      <li> <%= link_to 'Список всех пользователей', users_path %> </li>
    </ul>

    <ul class="nav pull-right">

    <% if user_signed_in? %>
      <li> <%= link_to 'Мои чаты', chat_rooms_path %> </li>
      <li class="hello-user">Здравствуйте, <%= current_user.name %></li>
      <li> <%= link_to 'Редактировать профиль', edit_user_registration_path %> </li>
      <li> <%= link_to 'Выйти', destroy_user_session_path, :method => :delete %> </li>
    <% else %>
      <li> <%= link_to 'Войти', new_user_session_path %> </li>
      <li> <%= link_to 'Зарегистрироваться', new_user_registration_path %> </li>
    <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Appv4</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= render 'layouts/header' %>

      <% flash.each do |key, value| %>
       <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>

      <%= yield %>

      <%= render 'layouts/footer' %>
  </body>
</html>